# -*- coding: utf-8 -*-
"""tugas_akhir_judul3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfMD0msu7oSghzUIE3khc46wdT7w9Txn
"""

def sequential_search(tas_senjata, target):
    indeks_ditemukan = []

    for i in range(len(tas_senjata)):
        if tas_senjata[i].lower() == target.lower():
            indeks_ditemukan.append(i)

    return indeks_ditemukan

def main():

    tas_senjata = [
        "Skyward Blade",
        "Rust",
        "Favonius Sword",
        "The Stringless",
        "Rust",
        "Aquila Favonia",
        "Sacrificial Sword",
        "Rust"
        "Favonius Sword",
        "The Stringless",
        "Rust",
        "Aquila Favonia",
        "Sacrificial Sword",
        "Rust",
    ]


    print("Daftar senjata dalam tas :")
    print(tas_senjata)


    target = input("\nMasukkan nama senjata yang ingin dicari : ")


    hasil = sequential_search(tas_senjata, target)


    if len(hasil) > 0:
        print(f"\nSenjata '{target}' ditemukan sebanyak {len(hasil)} kali.")
        print(f"Berada pada indeks: {hasil}")
    else:
        print(f"\nSenjata '{target}' tidak ditemukan dalam tas.")


if __name__ == "__main__":
    main()