# -*- coding: utf-8 -*-
"""Tugas_Akhir_Judul2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oRLKdUuOH0K5dv9zvHAdm5Ar5dMmJxk
"""

def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n - i - 1):
            if arr[j]["skor"] < arr[j + 1]["skor"]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]


def tampilkan(pemain):
    print("Peringkat  Nama            Skor")
    print("-" * 35)
    for i, p in enumerate(pemain, 1):
        print(f"{i:<11} {p['nama']:<16} {p['skor']}")


pemain = []

while True:
    try:
        n = int(input("Masukkan jumlah pemain: "))
        if n > 0:
            break
        print("Jumlah pemain harus lebih dari 0.")
    except ValueError:
        print("Harap masukkan angka yang valid!")

for i in range(n):
    print(f"\nPemain {i + 1}:")
    nama = input("  Nama  : ")

    while True:
        try:
            skor = int(input("  Skor  : "))
            break
        except ValueError:
            print("[Error] Skor harus berupa angka, Silakan coba lagi.")

    pemain.append({"nama": nama, "skor": skor})

print("\n=== Sebelum Diurutkan ===")
tampilkan(pemain)

bubble_sort(pemain)

print("\nSesudah Diurutkan (Descending)")
tampilkan(pemain)

print(f"\nPemenang : {pemain[0]['nama']} dengan skor {pemain[0]['skor']}!")