# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0XVmVo-FJB-FVxiTHdNs_iHKStJVqFx
"""

class Node:
    def __init__(self, key, value):
        self.key = key
        self.value = value
        self.next = None


class HashMapSeparateChaining:
    def __init__(self, size=10):
        self.SIZE = size
        self.table = [None] * self.SIZE

    def hash_function(self, key):
        return (key % self.SIZE + self.SIZE) % self.SIZE

    def insert(self, key, value):
        index = self.hash_function(key)
        current = self.table[index]
        while current is not None:
            if current.key == key:
                current.value = value
                return
            current = current.next
        new_node = Node(key, value)
        new_node.next = self.table[index]
        self.table[index] = new_node

    def search(self, key):
        index = self.hash_function(key)
        current = self.table[index]
        while current is not None:
            if current.key == key:
                return current
            current = current.next
        return None

    def remove_key(self, key):
        index = self.hash_function(key)
        current = self.table[index]
        prev = None
        while current is not None:
            if current.key == key:
                if prev is None:
                    self.table[index] = current.next
                else:
                    prev.next = current.next
                return True
            prev = current
            current = current.next
        return False

    def display(self):
        print("\nIsi Inventory kamu :")
        for i in range(self.SIZE):
            print(f"{i}: ", end="")
            current = self.table[i]
            while current is not None:
                print(f"({current.key},{current.value}) -> ", end="")
                current = current.next
            print("NULL")


def main():
    inventory = HashMapSeparateChaining()

    inventory.insert(1, "W-Engine: Demara Battery Mark II")
    inventory.insert(11, "Drive Disc: Shockstar Disco")
    inventory.insert(21, "Material: Senior Investigator Log")
    inventory.insert(2, "Item: Ether Battery")

    inventory.display()

    hasil = inventory.search(11)
    if hasil is not None:
        print(f"\nItem dengan key 11 ditemukan: {hasil.value}")
    else:
        print("\nItem dengan key 11 tidak ditemukan")

    inventory.remove_key(11)
    print("\nSetelah menghapus item dengan key 11:")
    inventory.display()


if __name__ == "__main__":
    main()
