# -*- coding: utf-8 -*-
"""Fachrezi Fajar Pratama_2515061119_Tugas Akhir Praktikum Struktur data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nz9OJC4pOQ0Qy36u9-iGSxNaH-2vbZ-P
"""

class Node:
    def __init__(self, lagu):
        self.lagu = lagu
        self.next = None


class Playlist:
    def __init__(self):
        self.head = None

    def tambah_lagu(self, lagu):
        new_node = Node(lagu)
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_node

    def hapus_lagu(self):
        if self.head is None:
            print("Playlist kamu kosong!")
        else:
            print(f"Lagu '{self.head.lagu}' telah dihapus")
            self.head = self.head.next

    def tampilkan(self):
        if self.head is None:
            print("Playlist kamu kosong!")
        else:
            current = self.head
            while current:
                print(current.lagu, end=" -> ")
                current = current.next
            print("Tidak ada lagu")


def main():
    playlist = Playlist()

    while True:
        print("\n=== MENU PLAYLIST ===")
        print("1. Tambah Lagu")
        print("2. Hapus Lagu Pertama")
        print("3. Tampilkan Playlist")
        print("4. Keluar")

        pilihan = input("Pilih menu: ")

        if pilihan == "1":
            lagu = input("Masukkan judul lagu: ")
            playlist.tambah_lagu(lagu)

        elif pilihan == "2":
            playlist.hapus_lagu()

        elif pilihan == "3":
            playlist.tampilkan()

        elif pilihan == "4":
            print("Program selesai.")
            break

        else:
            print("Pilihan tidak valid!")


if __name__ == "__main__":
    main()