# -*- coding: utf-8 -*-
"""tugas_akhir_judul4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHSe_Pxo9m_j3OkyG6YWPxMzB_rgi4Ap
"""

class QueueArray:
    def __init__(self, max_size=100):
        self.MAXN = max_size
        self.q = [None] * self.MAXN
        self.front_idx = -1
        self.rear_idx = -1

    def is_empty(self):
        return self.front_idx == -1

    def is_full(self):
        return (self.rear_idx + 1) % self.MAXN == self.front_idx

    def enqueue(self, karakter):
        if self.is_full():
            print("Urutan giliran penuh")
            return

        if self.is_empty():
            self.front_idx = 0
            self.rear_idx = 0
        else:
            self.rear_idx = (self.rear_idx + 1) % self.MAXN

        self.q[self.rear_idx] = karakter
        print(f"{karakter} masuk ke urutan giliran menyerang")

    def dequeue(self):
        if self.is_empty():
            print("Tidak ada karakter dalam giliran!")
            return

        print(f"{self.q[self.front_idx]} menyerang musuh!")

        if self.front_idx == self.rear_idx:
            self.front_idx = -1
            self.rear_idx = -1
        else:
            self.front_idx = (self.front_idx + 1) % self.MAXN

    def peek(self):
        if self.is_empty():
            print("Tidak ada karakter dalam giliran!")
            return

        print(f"Karakter yang akan menyerang berikutnya: {self.q[self.front_idx]}")

    def display(self):
        if self.is_empty():
            print("Urutan giliran kosong")
            return

        print("Urutan giliran menyerang: ", end="")
        i = self.front_idx

        while True:
            print(self.q[i], end="")
            if i == self.rear_idx:
                break
            print(" -> ", end="")
            i = (i + 1) % self.MAXN

        print()


def main():
    queue = QueueArray()
    pilih = 0

    while pilih != 5:
        print("\nGAME GILIRAN MENYERANG RPG HONKAI: STAR RAIL")
        print("1. Tambahkan karakter ke giliran")
        print("2. Karakter menyerang")
        print("3. Lihat karakter berikutnya")
        print("4. Tampilkan urutan giliran")
        print("5. Keluar")

        try:
            pilih = int(input("Pilih : "))
        except ValueError:
            print("Input tidak valid!")
            continue

        if pilih == 1:
            karakter = input("Masukkan nama karakter : ")
            queue.enqueue(karakter)

        elif pilih == 2:
            queue.dequeue()

        elif pilih == 3:
            queue.peek()

        elif pilih == 4:
            queue.display()

        elif pilih == 5:
            print("Pertarungan telah selesai.")

        else:
            print("Pilihan tidak valid!")


if __name__ == "__main__":
    main()